### ISSUE TITLE
update dsa-connect docs

### ISSUE THREAD

**Issue by pradyuman-verma** [Instadapp/docs#132]
- use version v2 in the docs

**Comment by chinmay0402** [comment]
# Setup Account

> Defi Account Setup

Every user needs to create a Smart Account to interact with DeFi protocols through Instadapp. These DeFi Smart Accounts (DSAs) allow developers to build extensible use-cases with maximum security and composability. It is also possible to create multiple DSAs for a single ethereum address.

The protocol provides three methods pertaining to setting up a DSA - 

- Create a Smart Account - `build()` 
- Fetch all Smart Accounts owned by an ethereum address - `getAccounts()`
- Set a Smart Account to be used for function calls - `setInstance()`

## build()
Used to create a new DSA account. For an already created account, you can use the `setInstance()` method to activate the particular DSA to start casting spells.
```
// in async functions
await dsa.build()

// or
dsa.build().then(console.log)
```
For implementations on NodeJs, it is required to pass the otherwise optional gasPrice parameter as well. There are also some other optional parameters that can be passed to the method as shown below  - 
```
dsa.build({
  gasPrice: gasPrice // estimated gas price
  origin: origin,
  authority: authority,
  version: 2
})
```
All the parameters that this method accepts are listed below - 
Parameter | Type | Description
|--------------|--------|----------------
| `gasPrice` | _string/number_ | The gas price in gwei. Mostly used in Node implementations to configure the transaction confirmation speed. 
| `origin` | _address_ | The address to track the origin of the transaction. Used for analytics and affiliates.
| `authority` | _address_ | The address to be added as the DSA authority.
| `from` | _address_ | The account with which you want to create your DSA. This is helpful to create DSA for other addresses.
| `nonce` | _string/number_ | Nonce of your sender account. Mostly  used in Node implementation to send transaction with a particular nonce either to override unconfirmed transaction or for other purposes.

The method returns the hash of the transaction and creates a uniquely numbered Smart Account which acts as a proxy to interact with verified DeFi protocols. Each DSA has a unique ethereum address. 

## getAccounts() 
Used to fetch all accounts owned by an ethereum address.
```
// in async functions
await dsa.getAccounts(address)

// or 
dsa.getAccounts(address).then(console.log)
```
Parameter | Type | Description
|--------------|--------|-----------------
|`address` _address_ The ethereum address for which the list of held DSA accounts is required.

The method returns an array of objects with all the DSA accounts which have the passed `address` as one of their authorities:
```
[
  {
      id: 52, // DSA ID
      address: "0x...", // DSA Address
      version: 2 // DSA protocol version
  },
  ...
]
```
## setInstance()
`setInstance()` method is used to configure global values and use the account having the `dsaId` equal to the passed Id for all subsequent operations.

```
dsa.setInstance(dsaId); // DSA ID
```

Parameters | Type | Description
|---------------|---------|----------------
| `dsaId` | _number_ | The DSA Id to be used for casting spells.|
```

**Comment by chinmay0402** [comment]
# Cast

> Casting Spells

A "spell" denotes a sequence of connector function calls that achieves a particular use case. Spells can comprise of any number of functions across any number of connectors. 
So, in essence, performing DeFi operations through Instadapp consists of creating a `Spell` instance to add transactions. This guide shows how you can use spells to perform operations in your dapp.

Create a "Spell" instance - 
```
let spells = dsa.Spell()
```

Add _spells_ for te transactions you want to execute in your dapp to this instance using the `add()` method. As an example, let's try to execute the following sequence of transactions using casting - 

- Deposit 1 ETH to Aave
- Borrow 100 DAI
- Deposit borrowed DAI on Compound

```
spells.add({
    connector: "AAVE-V2-A", // ID for AAVE connector
    method: "deposit",
    args: [
        "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE", // address to be used for ETH transactions on AAVE
        "1000000000000000000", // 1 ETH (10^18 wei)
        0,
        0
    ]
})

spells.add({
    connector: "AAVE-V2-A",
    method: "borrow",
    args: [
        "0x6B175474E89094C44Da98b954EedeAC495271d0F", // DAI token contract address
        "100000000000000000000",
        1, // rateMode - to decide between stable and variable interest rates while borrowing
        0,
        0
    ]
})

spells.add({
    connector: "COMPOUND-A", // ID for Compound connector
    method: "deposit",
    args: [
        "DAI-A", // DAI token id
        "100000000000000000000",
        0,
        0
    ]
})
```
_For more details on the arguments required for various methods in connectors, refer to the connector docs of the respective protocol (Connector docs for mainnet - https://docs.instadapp.io/connectors/mainnet)._

**Note**: Make sure your account has enough ETH (and ERC20) balance before executing transactions.

FInally, we execute the added spells using the `cast()` method.

```
// in async functions
let transactionHash = await spells.cast();

// or
spells.cast().then(console.log) // returns transaction hash
```

You can also pass an object to send optional parameters like sending ETH along with transaction.

```
spells.cast({
  gasPrice: web3.utils.toWei(gasPrice, 'gwei'), // in gwei, required in node implementation.
  value: "1000000000000000000", // sending 1 Eth along the transaction.
  nonce: nonce
})
```

Below is a list of all (optional) parameters you can pass with the `cast()` method - 
| Parameter | Type | Description |
|----------------|--------|----------------|
| `gasPrice` | _string/number_ | The gas price in gwei. Required in NodeJs implementation to configure the transaction confirmation speed.
| `value` | _string/number_ | The amount of ETH you want to send along with the transactions (in wei).
| `nonce` | _string/number_ | Nonce of your sender account. Mostly used in Node implementation to send transaction with a particular nonce either to override unconfirmed transaction or some other purpose.

This will send the transaction to blockchain in node implementation (or ask users to confirm the transaction on web3 wallet like Metamask).
